import {
  TrendingUp,
  Building2,
  Users,
  BedDouble,
  Wrench,
  CalendarDays,
  Hotel,
  Clock,
  Home,
  Sparkles,
  PackageCheck,
  FileBarChart2,
  UserCheck,
  LogOut,
  ClipboardCheck,
  AlertOctagon,
  CalendarRange,
} from "lucide-react";
import { TabConfig } from "./types";

export const TABS: TabConfig[] = [
  {
    id: "manager_flash",
    label: "Morning Operations Report",
    labelAr: "التقرير الصباحي الشامل",
    icon: <FileBarChart2 className="w-4 h-4 text-amber-500" />,
  },
  {
    id: "arrivals_manifest",
    label: "Expected Arrivals",
    labelAr: "كشف المتوقع وصولهم",
    icon: <UserCheck className="w-4 h-4 text-emerald-500" />,
  },
  {
    id: "departures_manifest",
    label: "Due Out & Departures",
    labelAr: "كشف المغادرات والتصفيات",
    icon: <LogOut className="w-4 h-4 text-rose-500" />,
  },
  {
    id: "housekeeping_sheet",
    label: "Attendant Task Sheet",
    labelAr: "كشف مهام الهاوس كيبنج",
    icon: <ClipboardCheck className="w-4 h-4 text-sky-500" />,
  },
  {
    id: "room_discrepancy",
    label: "Room Discrepancy & Audit",
    labelAr: "تدقيق ومطابقة الغرف",
    icon: <AlertOctagon className="w-4 h-4 text-red-500" />,
  },
  {
    id: "occupancy_forecast",
    label: "Occupancy Forecast",
    labelAr: "توقعات الإشغال المستقبلية",
    icon: <CalendarRange className="w-4 h-4 text-violet-500" />,
  },
  {
    id: "analytics",
    label: "Analytics",
    labelAr: "تحليلات عامة",
    icon: <TrendingUp className="w-4 h-4" />,
  },
  {
    id: "assignments",
    label: "In-House Occupants",
    labelAr: "المقيمين والتسكين",
    icon: <Users className="w-4 h-4 text-blue-500" />,
  },
  {
    id: "vacant_rooms",
    label: "Vacant Rooms & Beds",
    labelAr: "الغرف والأسرة الشاغرة",
    icon: <BedDouble className="w-4 h-4 text-emerald-500" />,
  },
  {
    id: "housing",
    label: "Room Occupancy",
    labelAr: "حالة وإشغال الغرف",
    icon: <Building2 className="w-4 h-4 text-sky-500" />,
  },
  {
    id: "equipment_inventory",
    label: "Amenities & Equipment Inventory",
    labelAr: "جرد المحتويات والمعدات",
    icon: <PackageCheck className="w-4 h-4 text-cyan-500" />,
  },
  {
    id: "profiles",
    label: "Profiles Directory",
    labelAr: "دليل البروفايلات",
    icon: <Hotel className="w-4 h-4 text-purple-500" />,
  },
  {
    id: "expiring_contracts",
    label: "Contract Expirations",
    labelAr: "انتهاء العقود",
    icon: <Clock className="w-4 h-4 text-amber-500" />,
  },
  {
    id: "reservations",
    label: "Arrivals & Reservations",
    labelAr: "الحجوزات والوصول",
    icon: <CalendarDays className="w-4 h-4 text-indigo-500" />,
  },
  {
    id: "hostings",
    label: "Guest Hostings",
    labelAr: "الاستضافات والزوار",
    icon: <Home className="w-4 h-4 text-teal-500" />,
  },
  {
    id: "maintenance",
    label: "Maintenance",
    labelAr: "طلبات الصيانة",
    icon: <Wrench className="w-4 h-4 text-rose-500" />,
  },
  {
    id: "housekeeping",
    label: "Housekeeping",
    labelAr: "هاوس كيبنج",
    icon: <Sparkles className="w-4 h-4 text-pink-500" />,
  },
];
