import {
  TrendingUp,
  Building2,
  Users,
  BedDouble,
  Wrench,
  CalendarDays,
  Hotel,
  Clock,
  Home,
  Sparkles,
  PackageCheck,
  FileBarChart2,
  UserCheck,
  LogOut,
  ClipboardCheck,
  AlertOctagon,
  CalendarRange,
  ArrowLeftRight,
  Briefcase,
  ShieldCheck,
  ShieldAlert,
  Star,
  Droplets,
  Scale,
  Palmtree,
  SlidersHorizontal,
  HeartHandshake,
} from "lucide-react";
import { TabConfig } from "./types";

export const TABS: TabConfig[] = [
  {
    id: "manager_flash",
    label: "Morning Operations Report",
    labelAr: "التقرير الصباحي الشامل",
    icon: <FileBarChart2 className="w-4 h-4 text-amber-500" />,
  },
  {
    id: "arrivals_manifest",
    label: "Reservations & Arrivals",
    labelAr: "الحجوزات والمتوقع وصولهم",
    icon: <UserCheck className="w-4 h-4 text-emerald-500" />,
  },
  {
    id: "departures_manifest",
    label: "Due Out & Departures",
    labelAr: "كشف المغادرات والتصفيات",
    icon: <LogOut className="w-4 h-4 text-rose-500" />,
  },
  {
    id: "housekeeping_sheet",
    label: "Housekeeping & Cleanliness",
    labelAr: "كشف مهام ونظافة الغرف",
    icon: <ClipboardCheck className="w-4 h-4 text-sky-500" />,
  },
  {
    id: "room_discrepancy",
    label: "Room Discrepancy & Audit",
    labelAr: "تدقيق ومطابقة الغرف",
    icon: <AlertOctagon className="w-4 h-4 text-red-500" />,
  },
  {
    id: "occupancy_forecast",
    label: "Occupancy Forecast",
    labelAr: "توقعات الإشغال المستقبلية",
    icon: <CalendarRange className="w-4 h-4 text-violet-500" />,
  },
  {
    id: "analytics",
    label: "Analytics",
    labelAr: "تحليلات عامة",
    icon: <TrendingUp className="w-4 h-4" />,
  },
  {
    id: "assignments",
    label: "In-House Occupants & Rooms",
    labelAr: "المقيمين والتسكين (بالغرف والنزلاء)",
    icon: <Users className="w-4 h-4 text-blue-500" />,
  },
  {
    id: "vacant_rooms",
    label: "Vacant Beds & Operational Capacity",
    labelAr: "مصفوفة السعة والأسرة الشاغرة",
    icon: <BedDouble className="w-4 h-4 text-emerald-500" />,
  },
  {
    id: "housing",
    label: "Complete Room Inventory",
    labelAr: "سجل وحالة كافة الغرف",
    icon: <Building2 className="w-4 h-4 text-sky-500" />,
  },
  {
    id: "daily_movement",
    label: "Daily Movement",
    labelAr: "الحركة اليومية",
    icon: <ArrowLeftRight className="w-4 h-4 text-blue-600" />,
  },
  {
    id: "department_occupancy",
    label: "Department Occupancy",
    labelAr: "إشغال الأقسام",
    icon: <Briefcase className="w-4 h-4 text-emerald-600" />,
  },
  {
    id: "gate_logs",
    label: "Gate Security Logs",
    labelAr: "سجل البوابة والأمن",
    icon: <ShieldCheck className="w-4 h-4 text-indigo-600" />,
  },
  {
    id: "police_report",
    label: "Tourism Police Manifest",
    labelAr: "كشف شرطة ووزارة السياحة",
    icon: <ShieldAlert className="w-4 h-4 text-blue-700" />,
  },
  {
    id: "equipment_inventory",
    label: "Amenities & Equipment Inventory",
    labelAr: "جرد المحتويات والمعدات",
    icon: <PackageCheck className="w-4 h-4 text-cyan-500" />,
  },
  {
    id: "profiles",
    label: "Profiles Directory",
    labelAr: "دليل البروفايلات",
    icon: <Hotel className="w-4 h-4 text-purple-500" />,
  },
  {
    id: "expiring_contracts",
    label: "Contract Expirations",
    labelAr: "انتهاء العقود",
    icon: <Clock className="w-4 h-4 text-amber-500" />,
  },
  {
    id: "hostings",
    label: "Guest Hostings",
    labelAr: "الاستضافات والزوار",
    icon: <Home className="w-4 h-4 text-teal-500" />,
  },
  {
    id: "maintenance",
    label: "Maintenance",
    labelAr: "طلبات الصيانة",
    icon: <Wrench className="w-4 h-4 text-rose-500" />,
  },
  {
    id: "service_ratings",
    label: "Service Quality & Ratings",
    labelAr: "تقييمات جودة الصيانة والنظافة",
    icon: <Star className="w-4 h-4 text-amber-500" />,
  },
  {
    id: "housing_map",
    label: "Housing Map & Structure",
    labelAr: "خريطة وتفصيل السكن والمباني",
    icon: <Building2 className="w-4 h-4 text-indigo-500" />,
  },
  {
    id: "water_distribution",
    label: "Water Distribution Sheet",
    labelAr: "كشف صرف مياه الشرب الشهري",
    icon: <Droplets className="w-4 h-4 text-cyan-500" />,
  },
  {
    id: "vacations",
    label: "Staff Vacations & Historical Archive",
    labelAr: "سجل وأرشيف إجازات الموظفين",
    icon: <Palmtree className="w-4 h-4 text-emerald-600" />,
  },
  {
    id: "policy_exceptions",
    label: "Policy Exceptions & Level Audit",
    labelAr: "تقرير استثناءات ومخالفات السياسة",
    icon: <Scale className="w-4 h-4 text-rose-600" />,
  },
  {
    id: "housing_ratings",
    label: "Weekly Housing Pulse",
    labelAr: "استطلاع جودة السكن الأسبوعي",
    icon: <HeartHandshake className="w-4 h-4 text-emerald-500" />,
  },
  {
    id: "room_moves",
    label: "Room Moves & Bed Transfers",
    labelAr: "حركات نقل وتغيير الغرف (Room Moves)",
    icon: <ArrowLeftRight className="w-4 h-4 text-indigo-500" />,
  },
];
