import { precacheAndRoute } from "workbox-precaching";
import { clientsClaim } from "workbox-core";
import { NavigationRoute, registerRoute } from "workbox-routing";
import { CacheFirst } from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";

// Precache all assets generated by vite build
precacheAndRoute(self.__WB_MANIFEST);

// Skip waiting and claim clients immediately
self.skipWaiting();
clientsClaim();

// Navigation fallback — serve index.html for all SPA navigation requests
registerRoute(
  new NavigationRoute(
    async ({ request }) => {
      try {
        const cache = await caches.open("workbox-precache");
        const cachedResponse = await cache.match("/index.html");
        if (cachedResponse) return cachedResponse;
        return await fetch(request);
      } catch {
        const cache = await caches.open("workbox-precache");
        const fallback = await cache.match("/index.html");
        return (
          fallback ||
          new Response(
            "<!doctype html><html><head><meta charset='UTF-8'><title>Offline</title></head><body style='background:#0d0f14;color:#fff;display:flex;align-items:center;justify-content:center;height:100vh;font-family:sans-serif;'><h2>Sunrise Portal Offline</h2></body></html>",
            { status: 200, headers: { "Content-Type": "text/html; charset=utf-8" } }
          )
        );
      }
    },
    {
      denylist: [/^\/api\//, /^\/ws/, /\.[a-zA-Z0-9]+$/],
    },
  ),
);

// Images — CacheFirst (30 days)
registerRoute(
  ({ request }) => request.destination === "image",
  new CacheFirst({
    cacheName: "image-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30,
      }),
    ],
  }),
);

// Fonts — CacheFirst (365 days)
registerRoute(
  ({ url }) =>
    url.origin === "https://fonts.googleapis.com" ||
    url.origin === "https://fonts.gstatic.com",
  new CacheFirst({
    cacheName: "font-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 60 * 60 * 24 * 365,
      }),
    ],
  }),
);

// ═══════════════════════════════════════════════════════════
// PUSH NOTIFICATION HANDLERS
// ═══════════════════════════════════════════════════════════

// Handle incoming push events
self.addEventListener("push", (event) => {
  if (!event.data) return;

  let data;
  try {
    data = event.data.json();
  } catch {
    data = { title: "Sunrise Housing", body: event.data.text() };
  }

  const title = data.title || "Sunrise Housing";
  const options = {
    body: data.body || "",
    icon: data.icon || "/pwa-192x192.png",
    badge: data.badge || "/pwa-192x192.png",
    tag: data.tag || "sunrise-notification",
    data: data.data || { url: "/dashboard" },
    vibrate: [200, 100, 200],
    requireInteraction: false,
    actions: data.actions || [],
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

// Handle notification click — open/focus the app
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = event.notification.data?.url || "/dashboard";

  event.waitUntil(
    clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((windowClients) => {
        for (const client of windowClients) {
          if (client.url.includes(self.location.origin) && "focus" in client) {
            client.navigate(url);
            return client.focus();
          }
        }
        if (clients.openWindow) {
          return clients.openWindow(url);
        }
      }),
  );
});
