/**
 * lib/db/src/schema/profile_portal.ts
 *
 * New table: profile_portal_accounts
 * - Stores portal credentials separately from HR profiles table
 * - Temporary passwords are generated by admin flows, must_change_password = true on first login
 * - Links to profiles.profile_id (the HR ID, not the DB row id)
 */

import {
  pgTable,
  text,
  serial,
  integer,
  boolean,
  timestamp,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const profilePortalAccountsTable = pgTable("profile_portal_accounts", {
  id: serial("id").primaryKey(),
  profileId: text("profile_id").notNull(), // HR profile ID (e.g. "EMP-001")
  passwordHash: text("password_hash").notNull(), // bcrypt hash
  mustChangePassword: boolean("must_change_password").notNull().default(true),
  isActive: boolean("is_active").notNull().default(true),
  failedAttempts: integer("failed_attempts").notNull().default(0),
  lockedUntil: timestamp("locked_until", { withTimezone: true }),
  resetRequired: boolean("reset_required").notNull().default(false),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  passwordChangedAt: timestamp("password_changed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
}, (table) => [
  uniqueIndex("uq_portal_accounts_profile_id").on(table.profileId),
  index("idx_portal_accounts_is_active").on(table.isActive),
]);

export const insertProfilePortalAccountSchema = createInsertSchema(
  profilePortalAccountsTable,
).omit({ id: true, createdAt: true, updatedAt: true });

export type InsertProfilePortalAccount = z.infer<
  typeof insertProfilePortalAccountSchema
>;
export type ProfilePortalAccount =
  typeof profilePortalAccountsTable.$inferSelect;

export const passwordResetTokensTable = pgTable("password_reset_tokens", {
  id: serial("id").primaryKey(),
  profileId: text("profile_id").notNull(),
  propertyId: integer("property_id").notNull(),
  tokenHash: text("token_hash").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  usedAt: timestamp("used_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
}, (table) => [
  index("idx_reset_tokens_profile_id").on(table.profileId),
  index("idx_reset_tokens_token_hash").on(table.tokenHash),
  index("idx_reset_tokens_expires_at").on(table.expiresAt),
]);

export const insertPasswordResetTokenSchema = createInsertSchema(
  passwordResetTokensTable,
).omit({ id: true, createdAt: true });

export type InsertPasswordResetToken = z.infer<
  typeof insertPasswordResetTokenSchema
>;
export type PasswordResetToken = typeof passwordResetTokensTable.$inferSelect;
