import {
  pgTable,
  text,
  serial,
  integer,
  timestamp,
  boolean,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const settingsTable = pgTable("settings", {
  id: serial("id").primaryKey(),
  systemName: text("system_name").notNull().default("Sunrise Staff Housing"),
  systemLogo: text("system_logo"),
  defaultLanguage: text("default_language").notNull().default("en"),
  primaryColor: text("primary_color").notNull().default("#0F2A44"),
  sidebarColor: text("sidebar_color").notNull().default("#1e293b"),
  buttonColor: text("button_color").notNull().default("#C9A24D"),
  departureAlertsEnabled: boolean("departure_alerts_enabled")
    .notNull()
    .default(true),
  departureAlertThreshold: integer("departure_alert_threshold")
    .notNull()
    .default(3),
  reportFooter: text("report_footer")
    .notNull()
    .default("Generated by Sunrise Housing System"),
  portalContactEmail: text("portal_contact_email"),
  portalContactPhone: text("portal_contact_phone"),
  portalContactExt: text("portal_contact_ext"),

  // ─── Password Policy ──────────────────────────────────────────────
  passwordMinLength: integer("password_min_length").notNull().default(8),
  passwordRequireUppercase: boolean("password_require_uppercase")
    .notNull()
    .default(true),
  passwordRequireLowercase: boolean("password_require_lowercase")
    .notNull()
    .default(true),
  passwordRequireNumber: boolean("password_require_number")
    .notNull()
    .default(true),
  passwordRequireSymbol: boolean("password_require_symbol")
    .notNull()
    .default(false),
  passwordExpiryDays: integer("password_expiry_days").notNull().default(90),
  passwordHistoryCount: integer("password_history_count").notNull().default(5),

  // ─── Account Lockout Policy ──────────────────────────────────────
  lockoutThreshold: integer("lockout_threshold").notNull().default(5),
  lockoutDurationMinutes: integer("lockout_duration_minutes")
    .notNull()
    .default(15),

  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const insertSettingsSchema = createInsertSchema(settingsTable).omit({
  id: true,
  updatedAt: true,
});
export type InsertSettings = z.infer<typeof insertSettingsSchema>;
export type Settings = typeof settingsTable.$inferSelect;
