import {
  pgTable,
  text,
  serial,
  integer,
  timestamp,
  boolean,
  jsonb,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const settingsTable = pgTable("settings", {
  id: serial("id").primaryKey(),
  systemName: text("system_name").notNull().default("Sunrise Staff Housing"),
  systemLogo: text("system_logo"),
  defaultLanguage: text("default_language").notNull().default("en"),
  primaryColor: text("primary_color").notNull().default("#0F2A44"),
  sidebarColor: text("sidebar_color").notNull().default("#1e293b"),
  buttonColor: text("button_color").notNull().default("#C9A24D"),
  departureAlertsEnabled: boolean("departure_alerts_enabled")
    .notNull()
    .default(true),
  departureAlertThreshold: integer("departure_alert_threshold")
    .notNull()
    .default(3),
  reportFooter: text("report_footer")
    .notNull()
    .default("Generated by Sunrise Housing System"),
  portalContactEmail: text("portal_contact_email"),
  portalContactPhone: text("portal_contact_phone"),
  portalContactExt: text("portal_contact_ext"),

  // ─── Password Policy ──────────────────────────────────────────────
  passwordMinLength: integer("password_min_length").notNull().default(8),
  passwordRequireUppercase: boolean("password_require_uppercase")
    .notNull()
    .default(true),
  passwordRequireLowercase: boolean("password_require_lowercase")
    .notNull()
    .default(true),
  passwordRequireNumber: boolean("password_require_number")
    .notNull()
    .default(true),
  passwordRequireSymbol: boolean("password_require_symbol")
    .notNull()
    .default(false),
  passwordExpiryDays: integer("password_expiry_days").notNull().default(90),
  passwordHistoryCount: integer("password_history_count").notNull().default(5),

  // ─── Account Lockout Policy ──────────────────────────────────────
  lockoutThreshold: integer("lockout_threshold").notNull().default(5),
  lockoutDurationMinutes: integer("lockout_duration_minutes")
    .notNull()
    .default(15),

  // ─── Email (SMTP) Configuration ──────────────────────────────────
  smtpHost: text("smtp_host"),
  smtpPort: integer("smtp_port").notNull().default(587),
  smtpSecure: boolean("smtp_secure").notNull().default(false),
  smtpUser: text("smtp_user"),
  smtpPass: text("smtp_pass"),
  smtpFrom: text("smtp_from"),

  // ─── Housing Allocation Policy ──────────────────────────────────────
  policyLevel0Capacity: integer("policy_level_0_capacity").notNull().default(1),
  policyLevel1Capacity: integer("policy_level_1_capacity").notNull().default(1),
  policyLevel2Capacity: integer("policy_level_2_capacity").notNull().default(2),
  policyLevel3Capacity: integer("policy_level_3_capacity").notNull().default(3),
  policyLevel4Capacity: integer("policy_level_4_capacity").notNull().default(4),
  policyLevel5Capacity: integer("policy_level_5_capacity").notNull().default(5),
  policyLevel6Capacity: integer("policy_level_6_capacity").notNull().default(6),
  policyLevel0AllowEntire: boolean("policy_level_0_allow_entire").notNull().default(true),
  policyLevel1AllowEntire: boolean("policy_level_1_allow_entire").notNull().default(true),
  policyLevel2AllowEntire: boolean("policy_level_2_allow_entire").notNull().default(false),
  policyLevel5AllowEntire: boolean("policy_level_5_allow_entire").notNull().default(false),
  policyLevel6AllowEntire: boolean("policy_level_6_allow_entire").notNull().default(false),
  customLevelRules: jsonb("custom_level_rules").default([]),
  policyDepartmentClustering: boolean("policy_department_clustering").notNull().default(true),
  policyStrictDepartmentSegregation: boolean("policy_strict_department_segregation").notNull().default(false),

  // ─── Family Visit Policy ──────────────────────────────────────────
  visitMaxNights: integer("visit_max_nights").notNull().default(7),
  visitMaxVisitsPerYear: integer("visit_max_visits_per_year").notNull().default(2),
  visitMinServiceMonths: integer("visit_min_service_months").notNull().default(6),
  visitCooldownDays: integer("visit_cooldown_days").notNull().default(90),
  visitRequireNationalId: boolean("visit_require_national_id").notNull().default(true),

  // ─── Housing Rules & Documentation ─────────────────────────────────
  curfewEnabled: boolean("curfew_enabled").notNull().default(false),
  curfewTime: text("curfew_time").notNull().default("23:00"),
  housingRulesText: text("housing_rules_text").default(""),
  familyVisitPolicyText: text("family_visit_policy_text").default(""),
  housingPolicyText: text("housing_policy_text").default(""),

  // ─── Key Contacts (HR 1 & 2, Housing Manager 1 & 2) ────────────────
  hrContact1Name: text("hr_contact_1_name").default(""),
  hrContact1Title: text("hr_contact_1_title").default("HR Manager"),
  hrContact1Phone: text("hr_contact_1_phone").default(""),
  hrContact1Email: text("hr_contact_1_email").default(""),

  hrContact2Name: text("hr_contact_2_name").default(""),
  hrContact2Title: text("hr_contact_2_title").default("Assistant HR Manager"),
  hrContact2Phone: text("hr_contact_2_phone").default(""),
  hrContact2Email: text("hr_contact_2_email").default(""),

  housingManager1Name: text("housing_manager_1_name").default(""),
  housingManager1Title: text("housing_manager_1_title").default("Housing Manager"),
  housingManager1Phone: text("housing_manager_1_phone").default(""),
  housingManager1Email: text("housing_manager_1_email").default(""),

  housingManager2Name: text("housing_manager_2_name").default(""),
  housingManager2Title: text("housing_manager_2_title").default("Assistant Housing Manager"),
  housingManager2Phone: text("housing_manager_2_phone").default(""),
  housingManager2Email: text("housing_manager_2_email").default(""),

  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const insertSettingsSchema = createInsertSchema(settingsTable).omit({
  id: true,
  updatedAt: true,
});
export type InsertSettings = z.infer<typeof insertSettingsSchema>;
export type Settings = typeof settingsTable.$inferSelect;
